<?php

use Illuminate\Support\Facades\Schema;
use Illuminate\Database\Schema\Blueprint;
use Illuminate\Database\Migrations\Migration;

/**
 * Migration auto-generated by Sequel Pro Laravel Export (1.8.1)
 * @see https://github.com/cviebrock/sequel-pro-laravel-export
 */
class AddForeignKeyToSongSonglistsTable extends Migration
{
    /**
     * Run the migrations.
     *
     * @return void
     */
    public function up()
    {
        Schema::table('song_songlists', function (Blueprint $table) {
            $table->foreign('song_id')->references('id')->on('songs');
            $table->foreign('songlist_id')->references('id')->on('songlists');
        });
    }

    /**
     * Reverse the migrations.
     *
     * @return void
     */
    public function down()
    {
        Schema::table('song_songlists', function (Blueprint $table) {
            $table->dropForeign('song_songlists_song_id_foreign');
            $table->dropForeign('song_songlists_songlist_id_foreign');
        });
    }
}
