<?php

use Illuminate\Support\Facades\Schema;
use Illuminate\Database\Schema\Blueprint;
use Illuminate\Database\Migrations\Migration;

/**
 * Migration auto-generated by Sequel Pro/Ace Laravel Export (1.8.1)
 * @see https://github.com/cviebrock/sequel-pro-laravel-export
 */
class CreateSongsTable extends Migration
{
    /**
     * Run the migrations.
     *
     * @return void
     */
    public function up()
    {
        Schema::create('songs', function (Blueprint $table) {
            $table->id();
            $table->string('name', 255);
            $table->string('artist', 255);
            $table->bigInteger('created_by')->default(0);
            $table->string('singer', 255)->nullable();
            $table->string('solo', 255)->nullable();
            $table->tinyInteger('keyboard')->nullable();
            $table->tinyInteger('acoustic')->nullable();
            $table->text('notes')->nullable();
            $table->integer('time')->nullable();
            $table->bigInteger('status_id')->nullable();
            $table->nullableTimestamps();
            $table->bigInteger('user_id')->nullable()->default(1);

            $table->charset = 'utf8mb4';
            $table->collation = 'utf8mb4_unicode_ci';
        });
        
    }

    /**
     * Reverse the migrations.
     *
     * @return void
     */
    public function down()
    {
        Schema::dropIfExists('songs');
    }
}
